export const FETCH_CONTACT_DETAILS = "FETCH_CONTACT_DETAILS";
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const SET_IMAGE_FROM_IMAGE_PICKER = "SET_IMAGE_FROM_IMAGE_PICKER";
export const RESET_IMAGE_PICKER = "RESET_IMAGE_PICKER";
